<%@ Page Title="" Language="C#" MasterPageFile="~/Principal.Master" AutoEventWireup="true" CodeBehind="DetalledeCompra.aspx.cs" Inherits="Vistas.DetalledeCompra" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link href="css/DetalleDeCompra.css" rel="stylesheet" type="text/css" />
    </asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="contenido" runat="server">
    <h1>Asientos</h1>
    <h3>
        <asp:Image CssClass="imgasientos" ID="imgAsientos" runat="server" ImageUrl="~/imagenes/asientos.jpg" ViewStateMode="Disabled" />
    </h3>
    <p>
        &nbsp;
    </p>
    <table> 
        <tr>
            <td class="td">Seleccione su/s asiento/s: </td>
         </tr>
            </table>
    <h3>
                <asp:DropDownList ID="ddlAsiento" runat="server" CssClass="ddla" AutoPostBack="True" OnSelectedIndexChanged="ddlAsiento_SelectedIndexChanged">
                </asp:DropDownList>
                &nbsp;</h3>
    <h4>
        <asp:Label ID="lblAsientosSeleccionados" runat="server" Text="Asientos seleccionados:" Visible="False"></asp:Label>
    </h4>
    <asp:GridView ID="gvAsientos" runat="server" AutoGenerateDeleteButton="True" CssClass="gridas" AutoGenerateColumns="False" DataKeyNames="ID Asiento" OnRowDeleting="gvAsientos_RowDeleting">
        <Columns>
            <asp:BoundField DataField="ID Asiento" HeaderText="ID Asiento" ReadOnly="True" SortExpression="ID Asiento">
                <HeaderStyle CssClass="header-gv" />
                <ItemStyle CssClass="item-gv" />
            </asp:BoundField>
        </Columns>
    </asp:GridView>
    <br />
    <h1>
    <asp:Label ID="lblPromo" CssClass="tit" runat="server" Text="Promociones"></asp:Label>
    </h1>
    <div class="center">
        <asp:ListView ID="lvPromociones" runat="server" DataKeyNames="ID_Promocion" DataSourceID="SqlDataSourcePromociones" GroupItemCount="5" OnItemCommand="lvPromociones_ItemCommand">
            <GroupTemplate>
                <tr id="itemPlaceholderContainer" runat="server">
                    <td id="itemPlaceholder" runat="server"></td>
                </tr>
            </GroupTemplate>
            <ItemTemplate>
                <td runat="server" style="background-color: #000000; color: white; text-align: center; font-size: small;">
                    <asp:Label CssClass="lv-item1" ID="Nombre_PromocionLabel" runat="server" Text='<%# Eval("Nombre_Promocion") %>' />
                    <br />
                    <asp:Label CssClass="lv-item2" ID="Descripcion_PromocionLabel" runat="server" Text='<%# Eval("Descripcion_Promocion") %>' />
                    <br />
                    <asp:Image CssClass="imgprom" ID="imgPromocion" runat="server" ImageUrl='<%# Eval("Url_imagen") %>' />
                    <br />
                    <br />
                    <asp:TextBox ID="txtPromocion" runat="server" CssClass="txtpr"></asp:TextBox>
                    <br />
                    <br />
                    <asp:Button ID="btnValidar" runat="server" Text="Validar" CssClass="btnlvpr" CommandArgument='<%# Eval("ID_Promocion") %>' CommandName="eventoValidar" OnCommand="btnValidar_Command" ValidationGroup="Validar" />
                    <br />
                </td>
            </ItemTemplate>
            <LayoutTemplate>
                <table runat="server">
                    <tr runat="server">
                        <td runat="server">
                            <table id="groupPlaceholderContainer" runat="server" border="1" class="lv-item2">
                                <tr id="groupPlaceholder" runat="server">
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
            </LayoutTemplate>
        </asp:ListView>
    </div>
    <br />

    <h1>Candy</h1>
    <div class="center">
        <asp:ListView ID="lvArticulos" runat="server" DataKeyNames="ID_Articulo" DataSourceID="SqlDataSourceArticulos" GroupItemCount="5" OnItemDataBound="gvArticulos_ItemDataBound" OnItemCommand="lvArticulos_ItemCommand">
            <GroupTemplate>
                <tr id="itemPlaceholderContainer" runat="server">
                    <td id="itemPlaceholder" runat="server"></td>
                </tr>
            </GroupTemplate>
           
            <ItemTemplate>
                <td runat="server" style="background-color: #000000; color: white; text-align: center; font-size: small;">
                    <asp:Label CssClass="lv-item1" ID="Nombre_ArticuloLabel" runat="server" Text='<%# Bind("Nombre_Articulo") %>'></asp:Label>
                    <br />
                    <asp:Label CssClass="lv-item2" ID="Descripcion_ArticuloLabel" runat="server" Text='<%# Eval("Descripcion_Articulo") %>'></asp:Label>
                    <br />
                    Precio: $
				<asp:Label ID="PrecioLabel" runat="server" Text='<%# Eval("Precio") %>'></asp:Label>
                    <br />
                    <asp:Image CssClass="imgart" ID="Image2" runat="server" ImageUrl='<%# Eval("URL_Articulo") %>' />
                    <br />
                    <br />
                    <asp:DropDownList ID="ddlStock" runat="server" CssClass="ddlart" DataTextField="Stock_ddl" DataSourceID="ODS_ddlStock">
                    </asp:DropDownList>
                    <br />
                    <br />
                    <asp:Button ID="btnAgregar" runat="server" CssClass="btnlvpr" Text="Agregar" CommandArgument='<%# Eval("ID_Articulo") %>' CommandName="eventoAgregar" OnCommand="btnAgregar_Command" ValidationGroup="Agregar" />
                    <br />
                    <asp:HiddenField ID="hfStock" runat="server" Value='<%# Eval("Stock_Articulo") %>' />
                    <asp:ObjectDataSource ID="ODS_ddlStock" runat="server" SelectMethod="cargarddlStock" TypeName="Negocios.NegociosArticulos">
                        <SelectParameters>
                            <asp:ControlParameter ControlID="hfStock" Name="Stock" Type="String" PropertyName="Value" />
                        </SelectParameters>
                    </asp:ObjectDataSource>
                </td>
            </ItemTemplate>
            <LayoutTemplate>
                <table runat="server">
                    <tr runat="server">
                        <td runat="server">
                            <table id="groupPlaceholderContainer" runat="server" border="1" style="background-color: #FFFFFF; border-collapse: collapse; border-color: #999999; border-style: none; border-width: 1px; font-family: Verdana, Arial, Helvetica, sans-serif;">
                                <tr id="groupPlaceholder" runat="server">
                                </tr>
                            </table>
                        </td>
                    </tr>
                    <tr runat="server">
                        <td runat="server" style="text-align: center; background-color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; color: #FFFFFF; width: 100%;">
                            <asp:DataPager ID="DataPager1" runat="server" PageSize="5">
                                <Fields>
                                    <asp:NextPreviousPagerField ButtonType="Button" ShowFirstPageButton="True" ShowNextPageButton="False" ShowPreviousPageButton="False" />
                                    <asp:NumericPagerField />
                                    <asp:NextPreviousPagerField ButtonType="Button" ShowLastPageButton="True" ShowNextPageButton="False" ShowPreviousPageButton="False" />
                                </Fields>
                            </asp:DataPager>
                        </td>
                    </tr>
                </table>
            </LayoutTemplate>
        </asp:ListView>
    </div>
    <br />
    <h4>&nbsp;<asp:Label ID="lblArticulosSeleccionados" runat="server" Text="Articulos seleccionados:" Visible="False"></asp:Label>
    </h4>
    <asp:GridView ID="gvArticulos" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" CssClass="gridart" DataKeyNames="ID_Articulo,Nombre,Descripcion,Cantidad,Precio" OnRowDeleting="gvArticulos_RowDeleting">
        <Columns>
            <asp:BoundField DataField="Nombre" HeaderText="Articulo" ReadOnly="True" SortExpression="Nombre">
                <HeaderStyle CssClass="header-gv" />
                <ItemStyle CssClass="item-gv" />
            </asp:BoundField>
            <asp:BoundField DataField="Descripcion" HeaderText="Descripcion" ReadOnly="True" SortExpression="Descripcion">
                <HeaderStyle CssClass="header-gv" />
                <ItemStyle CssClass="item-gv" />
            </asp:BoundField>
            <asp:BoundField DataField="Cantidad" HeaderText="Cantidad" ReadOnly="True" SortExpression="Cantidad">
                <HeaderStyle CssClass="header-gv" />
                <ItemStyle CssClass="item-gv" />
            </asp:BoundField>
            <asp:BoundField DataField="Precio" HeaderText="Precio" ReadOnly="True" SortExpression="Precio">
                <HeaderStyle CssClass="header-gv" />
                <ItemStyle CssClass="item-gv" />
            </asp:BoundField>
        </Columns>
    </asp:GridView>
    <br />
    <h3>
        <asp:Button ID="btnFinalizar" runat="server" CssClass="btnes" Text="Finalizar Compra" OnClick="btnFinalizar_Click" ValidationGroup="Finalizar" />
        &nbsp;&nbsp;&nbsp;&nbsp;
				<asp:Button ID="btnCancelar" runat="server" CssClass="btnes" Text="Cancelar" OnClick="btnCancelar_Click"/>
    </h3>
    <br />
    <asp:SqlDataSource ID="SqlDataSourceAsientosDisponibles" runat="server" ConnectionString="<%$ ConnectionStrings:CinetecaConnectionString %>" SelectCommand="SP_AsientosDisponible" SelectCommandType="StoredProcedure">
        <SelectParameters>
            <asp:SessionParameter Name="ID_Pelicula" SessionField="ID_Pelicula" Type="String" />
            <asp:SessionParameter Name="ID_Sucursal" SessionField="ID_Sucursal" Type="String" />
            <asp:SessionParameter Name="Horario" SessionField="Horario" Type="String" />
            <asp:SessionParameter SessionField="Fecha" Name="Fecha" DbType="Date" />
        </SelectParameters>
    </asp:SqlDataSource>
    <asp:SqlDataSource ID="SqlDataSourceAsientosReservados" runat="server" ConnectionString="<%$ ConnectionStrings:CinetecaConnectionString %>" SelectCommand="SP_AsientosReservado" SelectCommandType="StoredProcedure"></asp:SqlDataSource>
    <asp:SqlDataSource ID="SqlDataSourceArticulos" runat="server" ConnectionString="<%$ ConnectionStrings:CinetecaConnectionString %>" SelectCommand="SP_ArticulosDisponible" SelectCommandType="StoredProcedure"></asp:SqlDataSource>
    <asp:SqlDataSource ID="SqlDataSourceArticulosSeleccionados" runat="server" ConnectionString="<%$ ConnectionStrings:CinetecaConnectionString %>" SelectCommand="SELECT * FROM [DetalleVentaArticulos]"></asp:SqlDataSource>
    <asp:SqlDataSource ID="SqlDataSourcePromociones" runat="server" ConnectionString="<%$ ConnectionStrings:CinetecaConnectionString %>" SelectCommand="SELECT * FROM [Promociones]"></asp:SqlDataSource>
    <br />
</asp:Content>
